//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm.ServicesClients.UserManagement.Role {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagement.Role.IRoleService")]
    public interface IRoleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetRole", ReplyAction="http://tempuri.org/IRoleService/GetRoleResponse")]
        RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto GetRole(string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetRole", ReplyAction="http://tempuri.org/IRoleService/GetRoleResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto> GetRoleAsync(string roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetAllRoles", ReplyAction="http://tempuri.org/IRoleService/GetAllRolesResponse")]
        RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto[] GetAllRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoleService/GetAllRoles", ReplyAction="http://tempuri.org/IRoleService/GetAllRolesResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto[]> GetAllRolesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoleServiceChannel : RobotArm.ServicesClients.UserManagement.Role.IRoleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoleServiceClient : System.ServiceModel.ClientBase<RobotArm.ServicesClients.UserManagement.Role.IRoleService>, RobotArm.ServicesClients.UserManagement.Role.IRoleService {
        
        public RoleServiceClient() {
        }
        
        public RoleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto GetRole(string roleId) {
            return base.Channel.GetRole(roleId);
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto> GetRoleAsync(string roleId) {
            return base.Channel.GetRoleAsync(roleId);
        }
        
        public RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto[] GetAllRoles() {
            return base.Channel.GetAllRoles();
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.UserManagement.DataContracts.RoleDto[]> GetAllRolesAsync() {
            return base.Channel.GetAllRolesAsync();
        }
    }
}
