//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm.ServicesContracts.UserManagement.FaultContracts
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFault", Namespace="http://schemas.datacontract.org/2004/07/RobotArm.ServicesContracts.UserManagement" +
        ".FaultContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RobotArm.ServicesContracts.UserManagement.FaultContracts.EntityNotFoundFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RobotArm.ServicesContracts.UserManagement.FaultContracts.ArgumentFault))]
    public partial class BaseFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityNotFoundFault", Namespace="http://schemas.datacontract.org/2004/07/RobotArm.ServicesContracts.UserManagement" +
        ".FaultContracts")]
    public partial class EntityNotFoundFault : RobotArm.ServicesContracts.UserManagement.FaultContracts.BaseFault
    {
        
        private string EntityNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityName
        {
            get
            {
                return this.EntityNameField;
            }
            set
            {
                this.EntityNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArgumentFault", Namespace="http://schemas.datacontract.org/2004/07/RobotArm.ServicesContracts.UserManagement" +
        ".FaultContracts")]
    public partial class ArgumentFault : RobotArm.ServicesContracts.UserManagement.FaultContracts.BaseFault
    {
        
        private string ArgumentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArgumentName
        {
            get
            {
                return this.ArgumentNameField;
            }
            set
            {
                this.ArgumentNameField = value;
            }
        }
    }
}
