//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm.ServicesClients.RobotArmControl.RobotProgram {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RobotArmControl.RobotProgram.IRobotProgramService")]
    public interface IRobotProgramService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetPrograms", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramsResponse")]
        RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[] GetPrograms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetPrograms", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramsResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[]> GetProgramsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetProgram", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramResponse")]
        RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto GetProgram(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetProgram", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto> GetProgramAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddProgram", ReplyAction="http://tempuri.org/IRobotProgramService/AddProgramResponse")]
        void AddProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddProgram", ReplyAction="http://tempuri.org/IRobotProgramService/AddProgramResponse")]
        System.Threading.Tasks.Task AddProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateProgram", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateProgramResponse")]
        void UpdateProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateProgram", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateProgramResponse")]
        System.Threading.Tasks.Task UpdateProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteProgram", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteProgramResponse")]
        void DeleteProgram(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteProgram", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteProgramResponse")]
        System.Threading.Tasks.Task DeleteProgramAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetStep", ReplyAction="http://tempuri.org/IRobotProgramService/GetStepResponse")]
        RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto GetStep(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetStep", ReplyAction="http://tempuri.org/IRobotProgramService/GetStepResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto> GetStepAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddStep", ReplyAction="http://tempuri.org/IRobotProgramService/AddStepResponse")]
        void AddStep(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddStep", ReplyAction="http://tempuri.org/IRobotProgramService/AddStepResponse")]
        System.Threading.Tasks.Task AddStepAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateStep", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateStepResponse")]
        void UpdateStep(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateStep", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateStepResponse")]
        System.Threading.Tasks.Task UpdateStepAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteStep", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteStepResponse")]
        void DeleteStep(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteStep", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteStepResponse")]
        System.Threading.Tasks.Task DeleteStepAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddCartesianPoint", ReplyAction="http://tempuri.org/IRobotProgramService/AddCartesianPointResponse")]
        void AddCartesianPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddCartesianPoint", ReplyAction="http://tempuri.org/IRobotProgramService/AddCartesianPointResponse")]
        System.Threading.Tasks.Task AddCartesianPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateCartesianPoint", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateCartesianPointResponse")]
        void UpdateCartesianPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateCartesianPoint", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateCartesianPointResponse")]
        System.Threading.Tasks.Task UpdateCartesianPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteCartesianPoint", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteCartesianPointResponse")]
        void DeleteCartesianPoint(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteCartesianPoint", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteCartesianPointResponse")]
        System.Threading.Tasks.Task DeleteCartesianPointAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddJointPoint", ReplyAction="http://tempuri.org/IRobotProgramService/AddJointPointResponse")]
        void AddJointPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddJointPoint", ReplyAction="http://tempuri.org/IRobotProgramService/AddJointPointResponse")]
        System.Threading.Tasks.Task AddJointPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateJointPoint", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateJointPointResponse")]
        void UpdateJointPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateJointPoint", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateJointPointResponse")]
        System.Threading.Tasks.Task UpdateJointPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteJointPoint", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteJointPointResponse")]
        void DeleteJointPoint(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteJointPoint", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteJointPointResponse")]
        System.Threading.Tasks.Task DeleteJointPointAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetStepDefinitions", ReplyAction="http://tempuri.org/IRobotProgramService/GetStepDefinitionsResponse")]
        RobotArm.ServicesContracts.RobotArmControl.DataContracts.StepDefinitionDto[] GetStepDefinitions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetStepDefinitions", ReplyAction="http://tempuri.org/IRobotProgramService/GetStepDefinitionsResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.StepDefinitionDto[]> GetStepDefinitionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRobotProgramServiceChannel : RobotArm.ServicesClients.RobotArmControl.RobotProgram.IRobotProgramService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RobotProgramServiceClient : System.ServiceModel.ClientBase<RobotArm.ServicesClients.RobotArmControl.RobotProgram.IRobotProgramService>, RobotArm.ServicesClients.RobotArmControl.RobotProgram.IRobotProgramService {
        
        public RobotProgramServiceClient() {
        }
        
        public RobotProgramServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RobotProgramServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotProgramServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotProgramServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[] GetPrograms() {
            return base.Channel.GetPrograms();
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[]> GetProgramsAsync() {
            return base.Channel.GetProgramsAsync();
        }
        
        public RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto GetProgram(System.Guid id) {
            return base.Channel.GetProgram(id);
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto> GetProgramAsync(System.Guid id) {
            return base.Channel.GetProgramAsync(id);
        }
        
        public void AddProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            base.Channel.AddProgram(program);
        }
        
        public System.Threading.Tasks.Task AddProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            return base.Channel.AddProgramAsync(program);
        }
        
        public void UpdateProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            base.Channel.UpdateProgram(program);
        }
        
        public System.Threading.Tasks.Task UpdateProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            return base.Channel.UpdateProgramAsync(program);
        }
        
        public void DeleteProgram(System.Guid id) {
            base.Channel.DeleteProgram(id);
        }
        
        public System.Threading.Tasks.Task DeleteProgramAsync(System.Guid id) {
            return base.Channel.DeleteProgramAsync(id);
        }
        
        public RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto GetStep(System.Guid id) {
            return base.Channel.GetStep(id);
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto> GetStepAsync(System.Guid id) {
            return base.Channel.GetStepAsync(id);
        }
        
        public void AddStep(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step) {
            base.Channel.AddStep(step);
        }
        
        public System.Threading.Tasks.Task AddStepAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step) {
            return base.Channel.AddStepAsync(step);
        }
        
        public void UpdateStep(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step) {
            base.Channel.UpdateStep(step);
        }
        
        public System.Threading.Tasks.Task UpdateStepAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.ProgramStepDto step) {
            return base.Channel.UpdateStepAsync(step);
        }
        
        public void DeleteStep(System.Guid id) {
            base.Channel.DeleteStep(id);
        }
        
        public System.Threading.Tasks.Task DeleteStepAsync(System.Guid id) {
            return base.Channel.DeleteStepAsync(id);
        }
        
        public void AddCartesianPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point) {
            base.Channel.AddCartesianPoint(point);
        }
        
        public System.Threading.Tasks.Task AddCartesianPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point) {
            return base.Channel.AddCartesianPointAsync(point);
        }
        
        public void UpdateCartesianPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point) {
            base.Channel.UpdateCartesianPoint(point);
        }
        
        public System.Threading.Tasks.Task UpdateCartesianPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.CartesianPointDto point) {
            return base.Channel.UpdateCartesianPointAsync(point);
        }
        
        public void DeleteCartesianPoint(System.Guid id) {
            base.Channel.DeleteCartesianPoint(id);
        }
        
        public System.Threading.Tasks.Task DeleteCartesianPointAsync(System.Guid id) {
            return base.Channel.DeleteCartesianPointAsync(id);
        }
        
        public void AddJointPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point) {
            base.Channel.AddJointPoint(point);
        }
        
        public System.Threading.Tasks.Task AddJointPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point) {
            return base.Channel.AddJointPointAsync(point);
        }
        
        public void UpdateJointPoint(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point) {
            base.Channel.UpdateJointPoint(point);
        }
        
        public System.Threading.Tasks.Task UpdateJointPointAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.JointPointDto point) {
            return base.Channel.UpdateJointPointAsync(point);
        }
        
        public void DeleteJointPoint(System.Guid id) {
            base.Channel.DeleteJointPoint(id);
        }
        
        public System.Threading.Tasks.Task DeleteJointPointAsync(System.Guid id) {
            return base.Channel.DeleteJointPointAsync(id);
        }
        
        public RobotArm.ServicesContracts.RobotArmControl.DataContracts.StepDefinitionDto[] GetStepDefinitions() {
            return base.Channel.GetStepDefinitions();
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.StepDefinitionDto[]> GetStepDefinitionsAsync() {
            return base.Channel.GetStepDefinitionsAsync();
        }
    }
}
