//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotArm.ServicesClients.RobotArmControl.RobotProgram {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RobotArmControl.RobotProgram.IRobotProgramService")]
    public interface IRobotProgramService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetPrograms", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramsResponse")]
        RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[] GetPrograms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetPrograms", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramsResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[]> GetProgramsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetProgram", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramResponse")]
        RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto GetProgram(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/GetProgram", ReplyAction="http://tempuri.org/IRobotProgramService/GetProgramResponse")]
        System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto> GetProgramAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddProgram", ReplyAction="http://tempuri.org/IRobotProgramService/AddProgramResponse")]
        void AddProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/AddProgram", ReplyAction="http://tempuri.org/IRobotProgramService/AddProgramResponse")]
        System.Threading.Tasks.Task AddProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateProgram", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateProgramResponse")]
        void UpdateProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/UpdateProgram", ReplyAction="http://tempuri.org/IRobotProgramService/UpdateProgramResponse")]
        System.Threading.Tasks.Task UpdateProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteProgram", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteProgramResponse")]
        void DeleteProgram(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotProgramService/DeleteProgram", ReplyAction="http://tempuri.org/IRobotProgramService/DeleteProgramResponse")]
        System.Threading.Tasks.Task DeleteProgramAsync(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRobotProgramServiceChannel : RobotArm.ServicesClients.RobotArmControl.RobotProgram.IRobotProgramService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RobotProgramServiceClient : System.ServiceModel.ClientBase<RobotArm.ServicesClients.RobotArmControl.RobotProgram.IRobotProgramService>, RobotArm.ServicesClients.RobotArmControl.RobotProgram.IRobotProgramService {
        
        public RobotProgramServiceClient() {
        }
        
        public RobotProgramServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RobotProgramServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotProgramServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotProgramServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[] GetPrograms() {
            return base.Channel.GetPrograms();
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto[]> GetProgramsAsync() {
            return base.Channel.GetProgramsAsync();
        }
        
        public RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto GetProgram(System.Guid id) {
            return base.Channel.GetProgram(id);
        }
        
        public System.Threading.Tasks.Task<RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto> GetProgramAsync(System.Guid id) {
            return base.Channel.GetProgramAsync(id);
        }
        
        public void AddProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            base.Channel.AddProgram(program);
        }
        
        public System.Threading.Tasks.Task AddProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            return base.Channel.AddProgramAsync(program);
        }
        
        public void UpdateProgram(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            base.Channel.UpdateProgram(program);
        }
        
        public System.Threading.Tasks.Task UpdateProgramAsync(RobotArm.ServicesContracts.RobotArmControl.DataContracts.RobotProgramDto program) {
            return base.Channel.UpdateProgramAsync(program);
        }
        
        public void DeleteProgram(System.Guid id) {
            base.Channel.DeleteProgram(id);
        }
        
        public System.Threading.Tasks.Task DeleteProgramAsync(System.Guid id) {
            return base.Channel.DeleteProgramAsync(id);
        }
    }
}
